SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

set(COMPILER_PREFIX "aarch64-linux-gnu")

find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc)
find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc)

